apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: couchsvc11
  name: couchsvc11
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 2m
      port: prom
      scrapeTimeout: 2m
    - interval1: 30s
      port: http1
  namespaceSelector:
    matchNames:
    - smartfan-dev-app
    - smartfan-devops-app
    
  selector:
    matchLabels:
      app: couchsvc11